# Generated by Django 3.2.12 on 2022-03-24 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'verbose_name': 'Review category',
                'verbose_name_plural': 'Review categories',
                'db_table': 'review_category',
            },
        ),
        migrations.CreateModel(
            name='ReviewBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='brand_images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'verbose_name': 'Review brand',
                'verbose_name_plural': 'Review brands',
                'db_table': 'review_brand',
            },
        ),
        migrations.AddIndex(
            model_name='reviewcategory',
            index=models.Index(fields=['id'], name='review_cate_id_733b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcategory',
            index=models.Index(fields=['name'], name='review_cate_name_a91abd_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcategory',
            index=models.Index(fields=['slug'], name='review_cate_slug_51b493_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewbrand',
            index=models.Index(fields=['id'], name='review_bran_id_bfb5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewbrand',
            index=models.Index(fields=['name'], name='review_bran_name_7cfe0b_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewbrand',
            index=models.Index(fields=['slug'], name='review_bran_slug_b0f334_idx'),
        ),
    ]
