# Generated by Django 3.2.12 on 2022-03-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220329_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='summary_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='summary_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='summary_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='summary_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
