# Generated by Django 3.2.12 on 2022-03-30 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220329_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewbrand',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reviewbrand'),
        ),
        migrations.AddField(
            model_name='reviewcategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reviewcategory'),
        ),
    ]
