# Generated by Django 3.2.12 on 2022-03-30 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220330_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reviewcategory'),
        ),
    ]
