# Generated by Django 3.2.12 on 2022-03-30 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_reviewcategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewbrand',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reviewbrand'),
        ),
    ]
