# Generated by Django 3.2.12 on 2022-03-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_reviewbrand_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewbrand',
            old_name='brand_image',
            new_name='brand_image_full',
        ),
        migrations.RenameField(
            model_name='reviewbrand',
            old_name='parent_category',
            new_name='parent_brand',
        ),
        migrations.RenameField(
            model_name='reviewcategory',
            old_name='category_image',
            new_name='category_image_full',
        ),
        migrations.AddField(
            model_name='reviewbrand',
            name='brand_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='brand_mobile_images/'),
        ),
        migrations.AddField(
            model_name='reviewbrand',
            name='brand_image_web',
            field=models.ImageField(blank=True, null=True, upload_to='brand_web_images/'),
        ),
        migrations.AddField(
            model_name='reviewbrand',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=50),
        ),
        migrations.AddField(
            model_name='reviewcategory',
            name='category_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='category_mobile_images/'),
        ),
        migrations.AddField(
            model_name='reviewcategory',
            name='category_image_web',
            field=models.ImageField(blank=True, null=True, upload_to='category_web_images/'),
        ),
        migrations.AddField(
            model_name='reviewcategory',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=50),
        ),
    ]
