# Generated by Django 3.2.12 on 2022-04-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220331_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewgalley',
            name='image',
            field=models.ImageField(upload_to='review_galley/'),
        ),
    ]
