# Generated by Django 3.2.12 on 2022-04-07 06:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_reviewgalley_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlight', models.CharField(blank=True, max_length=200, null=True)),
                ('taillight', models.CharField(blank=True, max_length=200, null=True)),
                ('fenders', models.CharField(blank=True, max_length=200, null=True)),
                ('front_rack', models.CharField(blank=True, max_length=200, null=True)),
                ('rear_rack', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review \tAccessory',
                'verbose_name_plural': 'Review Accessories',
                'db_table': 'review_accessory',
            },
        ),
        migrations.CreateModel(
            name='ReviewComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headset', models.CharField(blank=True, max_length=200, null=True)),
                ('stem', models.CharField(blank=True, max_length=200, null=True)),
                ('handlebar', models.CharField(blank=True, max_length=200, null=True)),
                ('grips', models.CharField(blank=True, max_length=200, null=True)),
                ('seatpost', models.CharField(blank=True, max_length=200, null=True)),
                ('seatpost_diameter', models.CharField(blank=True, max_length=200, null=True)),
                ('saddle', models.CharField(blank=True, max_length=200, null=True)),
                ('pedals', models.CharField(blank=True, max_length=200, null=True)),
                ('components_brake_type', models.CharField(blank=True, max_length=200, null=True)),
                ('front_brake', models.CharField(blank=True, max_length=200, null=True)),
                ('rear_brake', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Component',
                'verbose_name_plural': 'Review Components',
                'db_table': 'review_components',
            },
        ),
        migrations.CreateModel(
            name='ReviewDrivetrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivetrain_gears', models.CharField(blank=True, max_length=200, null=True)),
                ('shift_levers', models.CharField(blank=True, max_length=200, null=True)),
                ('front_derailleur', models.CharField(blank=True, max_length=200, null=True)),
                ('crankset', models.CharField(blank=True, max_length=200, null=True)),
                ('rear_derailleur', models.CharField(blank=True, max_length=200, null=True)),
                ('electronic_shifting', models.CharField(blank=True, max_length=200, null=True)),
                ('internally_geared_hub', models.CharField(blank=True, max_length=200, null=True)),
                ('continually_variable_transmission', models.CharField(blank=True, max_length=200, null=True)),
                ('cassette', models.CharField(blank=True, max_length=200, null=True)),
                ('chainring', models.CharField(blank=True, max_length=200, null=True)),
                ('belt_drive', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Drivetrain',
                'verbose_name_plural': 'Review Drivetrains',
                'db_table': 'review_drivetrain',
            },
        ),
        migrations.CreateModel(
            name='ReviewEbikeSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systems_bike_class', models.CharField(blank=True, max_length=200, null=True)),
                ('systems_motor_type', models.CharField(blank=True, max_length=200, null=True)),
                ('motor', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_motors', models.CharField(blank=True, max_length=200, null=True)),
                ('systems_motor_nominal_output', models.CharField(blank=True, max_length=200, null=True)),
                ('display', models.CharField(blank=True, max_length=200, null=True)),
                ('smart_bike', models.CharField(blank=True, max_length=200, null=True)),
                ('theft_gps', models.CharField(blank=True, max_length=200, null=True)),
                ('systems_battery_watt_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('battery', models.CharField(blank=True, max_length=200, null=True)),
                ('charger', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Ebike System',
                'verbose_name_plural': 'Review Ebike Systems',
                'db_table': 'review_ebike_systems',
            },
        ),
        migrations.CreateModel(
            name='ReviewFrameset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameset_frame_type', models.CharField(blank=True, max_length=200, null=True)),
                ('frame', models.CharField(blank=True, max_length=200, null=True)),
                ('frameset_weight', models.CharField(blank=True, max_length=200, null=True)),
                ('load_capacity', models.CharField(blank=True, max_length=200, null=True)),
                ('frameset_suspension', models.CharField(blank=True, max_length=200, null=True)),
                ('fork', models.CharField(blank=True, max_length=200, null=True)),
                ('rear_shock', models.CharField(blank=True, max_length=200, null=True)),
                ('frameset_wheel_size', models.CharField(blank=True, max_length=200, null=True)),
                ('front_wheel', models.CharField(blank=True, max_length=200, null=True)),
                ('rear_wheel', models.CharField(blank=True, max_length=200, null=True)),
                ('front_hub', models.CharField(blank=True, max_length=200, null=True)),
                ('rear_hub', models.CharField(blank=True, max_length=200, null=True)),
                ('tires', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Frameset',
                'verbose_name_plural': 'Review Frameset',
                'db_table': 'review_frameset',
            },
        ),
        migrations.CreateModel(
            name='ReviewGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msrp', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('bike_class', models.CharField(blank=True, max_length=200, null=True)),
                ('frame_type', models.CharField(blank=True, max_length=200, null=True)),
                ('suspension', models.CharField(blank=True, max_length=200, null=True)),
                ('wheel_size', models.CharField(blank=True, max_length=200, null=True)),
                ('gears', models.CharField(blank=True, max_length=200, null=True)),
                ('brake_type', models.CharField(blank=True, max_length=200, null=True)),
                ('motor_type', models.CharField(blank=True, max_length=200, null=True)),
                ('motor_nominal_output', models.CharField(blank=True, max_length=200, null=True)),
                ('battery_watt_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review General',
                'verbose_name_plural': 'Review Generals',
                'db_table': 'review_general',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='model_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='model_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='trim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ReviewSpecification',
        ),
        migrations.AddField(
            model_name='reviewgeneral',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_general_review', to='core.review'),
        ),
        migrations.AddField(
            model_name='reviewframeset',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_frameset_review', to='core.review'),
        ),
        migrations.AddField(
            model_name='reviewebikesystems',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_ebike_systems_review', to='core.review'),
        ),
        migrations.AddField(
            model_name='reviewdrivetrain',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_drivetrain_review', to='core.review'),
        ),
        migrations.AddField(
            model_name='reviewcomponents',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_components_review', to='core.review'),
        ),
        migrations.AddField(
            model_name='reviewaccessories',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_accessory_review', to='core.review'),
        ),
    ]
