# Generated by Django 3.2.12 on 2022-04-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220407_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewgeneral',
            name='category',
        ),
    ]
