# Generated by Django 3.2.12 on 2022-04-20 11:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220415_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_filter', models.BooleanField(default=False)),
                ('footer_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'verbose_name': 'Pege',
                'verbose_name_plural': 'Pages',
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='PagesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tag', models.CharField(choices=[('Affordable', 'Affordable'), ('Honorable', 'Honorable'), ('Premium', 'Premium'), ('Promoted', 'Promoted'), ('Value', 'Value')], default='Promoted', max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_review_page', to='core.pages')),
                ('review', models.ManyToManyField(db_index=True, related_name='page_review_review', to='core.Review')),
            ],
            options={
                'verbose_name': 'Pege Review',
                'verbose_name_plural': 'Pages Reviews',
                'db_table': 'pages_review',
            },
        ),
        migrations.AddIndex(
            model_name='pages',
            index=models.Index(fields=['id'], name='pages_id_0e914f_idx'),
        ),
        migrations.AddIndex(
            model_name='pages',
            index=models.Index(fields=['slug'], name='pages_slug_2ebe9d_idx'),
        ),
    ]
