# Generated by Django 3.2.12 on 2022-04-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220425_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='footer_description',
        ),
        migrations.AddField(
            model_name='pages',
            name='query_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PagesReview',
        ),
    ]
