# Generated by Django 3.2.12 on 2022-04-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220427_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='query_text',
            new_name='search_text',
        ),
    ]
