# Generated by Django 3.2.12 on 2022-04-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_query_text_pages_search_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='meta_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
