# Generated by Django 3.2.12 on 2022-05-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220502_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='model_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='trim',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='brands',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='pages_brand', to='core.ReviewBrand'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='categories',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='pages_category', to='core.ReviewCategory'),
        ),
    ]
