# Generated by Django 3.2.12 on 2022-05-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220502_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='filter_type',
            field=models.BooleanField(choices=[(True, 'Basic Search Filter'), (False, 'Advanced Search Filter')], default='True'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='max_battery_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='max_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='max_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='min_battery_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='min_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='min_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
