# Generated by Django 3.2.12 on 2022-05-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pages_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('menu_type', models.CharField(choices=[('main_menu', 'Main Menu'), ('popular_brands', 'Popular Brands'), ('popular_categories', 'Popular Categories'), ('popular_searches', 'Popular Searches'), ('popular_topics', 'Popular Topics')], default='main_menu', max_length=255)),
                ('order', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.menus')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'menus',
            },
        ),
        migrations.AddIndex(
            model_name='menus',
            index=models.Index(fields=['id'], name='menus_id_c2772b_idx'),
        ),
        migrations.AddIndex(
            model_name='menus',
            index=models.Index(fields=['name', 'order'], name='menus_name_0f07a3_idx'),
        ),
    ]
