# Generated by Django 3.2.12 on 2022-05-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220504_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='menu_type',
        ),
        migrations.AddField(
            model_name='menus',
            name='menu_location',
            field=models.CharField(choices=[('main_menu', 'Main Menu'), ('popular_brands', 'Popular Brands'), ('popular_categories', 'Popular Categories'), ('popular_searches', 'Popular Searches'), ('popular_topics', 'Popular Topics'), ('footer_links', 'Footer Links')], default='main_menu', max_length=255),
        ),
    ]
