# Generated by Django 3.2.12 on 2022-05-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220504_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcategory',
            name='category_image_darkmode_full',
            field=models.ImageField(blank=True, null=True, upload_to='category_darkmode_images/'),
        ),
        migrations.AddField(
            model_name='reviewcategory',
            name='category_image_darkmode_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='category_mobile_darkmode_images/'),
        ),
        migrations.AddField(
            model_name='reviewcategory',
            name='category_image_darkmode_web',
            field=models.ImageField(blank=True, null=True, upload_to='category_web_darkmode_images/'),
        ),
        migrations.AddField(
            model_name='reviewcategory',
            name='category_image_grayscale_full',
            field=models.ImageField(blank=True, null=True, upload_to='category_grayscale_images/'),
        ),
        migrations.AddField(
            model_name='reviewcategory',
            name='category_image_grayscale_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='category_mobile_grayscale_images/'),
        ),
        migrations.AddField(
            model_name='reviewcategory',
            name='category_image_grayscale_web',
            field=models.ImageField(blank=True, null=True, upload_to='category_web_grayscale_images/'),
        ),
    ]
