# Generated by Django 3.2.12 on 2022-05-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220506_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcategory',
            name='category_image_darkmode_full',
        ),
        migrations.RemoveField(
            model_name='reviewcategory',
            name='category_image_darkmode_mobile',
        ),
        migrations.RemoveField(
            model_name='reviewcategory',
            name='category_image_darkmode_web',
        ),
        migrations.RemoveField(
            model_name='reviewcategory',
            name='category_image_grayscale_full',
        ),
        migrations.RemoveField(
            model_name='reviewcategory',
            name='category_image_grayscale_mobile',
        ),
        migrations.RemoveField(
            model_name='reviewcategory',
            name='category_image_grayscale_web',
        ),
        migrations.AddField(
            model_name='reviewbrand',
            name='brand_image_darkmode_full',
            field=models.ImageField(blank=True, null=True, upload_to='brand_darkmode_images/'),
        ),
        migrations.AddField(
            model_name='reviewbrand',
            name='brand_image_darkmode_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='brand_mobile_darkmode_images/'),
        ),
        migrations.AddField(
            model_name='reviewbrand',
            name='brand_image_darkmode_web',
            field=models.ImageField(blank=True, null=True, upload_to='brand_web_darkmode_images/'),
        ),
        migrations.AddField(
            model_name='reviewbrand',
            name='brand_image_grayscale_full',
            field=models.ImageField(blank=True, null=True, upload_to='brand_grayscale_images/'),
        ),
        migrations.AddField(
            model_name='reviewbrand',
            name='brand_image_grayscale_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='brand_mobile_grayscale_images/'),
        ),
        migrations.AddField(
            model_name='reviewbrand',
            name='brand_image_grayscale_web',
            field=models.ImageField(blank=True, null=True, upload_to='brand_web_grayscale_images/'),
        ),
    ]
