# Generated by Django 3.2.12 on 2022-05-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220506_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='review-featured-images/'),
        ),
        migrations.AlterField(
            model_name='reviewbrand',
            name='brand_image_darkmode_full',
            field=models.ImageField(blank=True, null=True, upload_to='brand-darkmode-images/'),
        ),
        migrations.AlterField(
            model_name='reviewbrand',
            name='brand_image_darkmode_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='brand-mobile-darkmode-images/'),
        ),
        migrations.AlterField(
            model_name='reviewbrand',
            name='brand_image_darkmode_web',
            field=models.ImageField(blank=True, null=True, upload_to='brand-web-darkmode-images/'),
        ),
        migrations.AlterField(
            model_name='reviewbrand',
            name='brand_image_full',
            field=models.ImageField(blank=True, null=True, upload_to='brand-images/'),
        ),
        migrations.AlterField(
            model_name='reviewbrand',
            name='brand_image_grayscale_full',
            field=models.ImageField(blank=True, null=True, upload_to='brand-grayscale-images/'),
        ),
        migrations.AlterField(
            model_name='reviewbrand',
            name='brand_image_grayscale_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='brand-mobile-grayscale-images/'),
        ),
        migrations.AlterField(
            model_name='reviewbrand',
            name='brand_image_grayscale_web',
            field=models.ImageField(blank=True, null=True, upload_to='brand-web-grayscale-images/'),
        ),
        migrations.AlterField(
            model_name='reviewbrand',
            name='brand_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='brand-mobile-images/'),
        ),
        migrations.AlterField(
            model_name='reviewbrand',
            name='brand_image_web',
            field=models.ImageField(blank=True, null=True, upload_to='brand-web-images/'),
        ),
        migrations.AlterField(
            model_name='reviewcategory',
            name='category_image_full',
            field=models.ImageField(blank=True, null=True, upload_to='category-images/'),
        ),
        migrations.AlterField(
            model_name='reviewcategory',
            name='category_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='category-mobile-images/'),
        ),
        migrations.AlterField(
            model_name='reviewcategory',
            name='category_image_web',
            field=models.ImageField(blank=True, null=True, upload_to='category-web-images/'),
        ),
    ]
