# Generated by Django 3.2.12 on 2022-05-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220509_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slide_link', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url_title', models.CharField(blank=True, max_length=100, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('Placements', models.CharField(choices=[('rail_ads', 'Rail Ads'), ('brand_ads', 'Brand Ads'), ('category_ads', 'Category Ads'), ('home_ads', 'Home Ads')], max_length=100)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='trusted-accessories-featured-images/')),
                ('background_color', models.CharField(blank=True, max_length=10, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='trusted-accessories-background-images/')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'verbose_name': 'Trusted Accessory',
                'verbose_name_plural': 'Trusted Accessories',
                'db_table': 'trusted_accessories',
            },
        ),
        migrations.AddIndex(
            model_name='trustedaccessories',
            index=models.Index(fields=['id'], name='trusted_acc_id_2f482a_idx'),
        ),
        migrations.AddIndex(
            model_name='trustedaccessories',
            index=models.Index(fields=['name'], name='trusted_acc_name_09868f_idx'),
        ),
    ]
