# Generated by Django 3.2.12 on 2022-05-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_imagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='thumbnail_image',
            field=models.ImageField(default='', upload_to='thumbnail-image-gallery'),
            preserve_default=False,
        ),
    ]
