# Generated by Django 3.2.12 on 2022-05-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_imagegallery_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewgalley',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagegallery'),
        ),
    ]
