# Generated by Django 3.2.12 on 2022-05-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_reviewgalley_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustedaccessories',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='trustedaccessories',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='trustedaccessories',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='trustedaccessories',
            name='button_url_title',
        ),
        migrations.RemoveField(
            model_name='trustedaccessories',
            name='placements',
        ),
        migrations.AddField(
            model_name='trustedaccessories',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trustedaccessories',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='trusted-images/'),
        ),
    ]
