# Generated by Django 3.2.12 on 2022-05-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_reviewframeset_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='summary_1',
        ),
        migrations.RemoveField(
            model_name='review',
            name='summary_2',
        ),
        migrations.RemoveField(
            model_name='review',
            name='summary_3',
        ),
        migrations.RemoveField(
            model_name='review',
            name='summary_4',
        ),
        migrations.CreateModel(
            name='ReviewHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_highlight', to='core.review')),
            ],
            options={
                'verbose_name': 'Review Highlight',
                'verbose_name_plural': 'Review Highlights',
                'db_table': 'review_highlight',
            },
        ),
    ]
