# Generated by Django 3.2.12 on 2022-05-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_review_more_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
