# Generated by Django 3.2.12 on 2022-06-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_reviewcategory_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcategory',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='category-icon-images/'),
        ),
    ]
