# Generated by Django 3.2.12 on 2022-06-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20220613_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='featured_image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='review-featured-images-thumbnail/'),
        ),
        migrations.AddField(
            model_name='review',
            name='featured_image_web',
            field=models.ImageField(blank=True, null=True, upload_to='review-featured-images-web/'),
        ),
    ]
