# Generated by Django 3.2.12 on 2022-06-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20220627_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewebikesystems',
            name='additional_battery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
