# Generated by Django 3.2.12 on 2022-07-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_reviewebikesystems_additional_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewbrand',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
