# Generated by Django 3.2.12 on 2022-07-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_reviewbrand_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcsv1',
            name='Additional_Battery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
