# Generated by Django 3.2.12 on 2022-07-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_reviewcsv1_additional_battery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewCSV1',
        ),
    ]
