# Generated by Django 3.2.12 on 2022-07-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_reviewcsv1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewframeset',
            name='suspension_travel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
