# Generated by Django 3.2.12 on 2022-08-10 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20220809_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comments')),
            ],
            options={
                'verbose_name': 'upvote',
                'verbose_name_plural': 'upvotes',
                'db_table': 'upvote',
            },
        ),
        migrations.AddIndex(
            model_name='upvote',
            index=models.Index(fields=['id'], name='upvote_id_f614d9_idx'),
        ),
        migrations.AddIndex(
            model_name='upvote',
            index=models.Index(fields=['ip'], name='upvote_ip_72cc4d_idx'),
        ),
    ]
