# Generated by Django 3.2.12 on 2022-08-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_comments_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
