# Generated by Django 3.2.12 on 2022-08-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_comments_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_class', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bike_class_changes',
            },
        ),
        migrations.CreateModel(
            name='BreakType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'break_type_changes',
            },
        ),
        migrations.CreateModel(
            name='FrameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_type', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'frame_type_changes',
            },
        ),
        migrations.CreateModel(
            name='ModelYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'model_year_changes',
            },
        ),
        migrations.CreateModel(
            name='WheelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_size', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'wheel_size_changes',
            },
        ),
        migrations.AddField(
            model_name='reviewcomponents',
            name='demo_seatpost_diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewdrivetrain',
            name='demo_drivetrain_gears',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewebikesystems',
            name='demo_systems_battery_watt_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewebikesystems',
            name='demo_systems_motor_nominal_output',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewframeset',
            name='demo_frameset_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewframeset',
            name='demo_suspension_travel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewgeneral',
            name='demo_battery_watt_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewgeneral',
            name='demo_gear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewgeneral',
            name='demo_motor_nominal_output',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewgeneral',
            name='demo_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='demo_page_bike_class',
            field=models.ManyToManyField(db_index=True, related_name='demo_page_bike_class_changes', to='core.BikeClass'),
        ),
        migrations.AddField(
            model_name='review',
            name='demo_model_year',
            field=models.ManyToManyField(blank=True, related_name='demo_model_year_changes', to='core.ModelYear'),
        ),
        migrations.AddField(
            model_name='reviewcomponents',
            name='demo_components_brake_type',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demo_components_brake_type_changes', to='core.BreakType'),
        ),
        migrations.AddField(
            model_name='reviewebikesystems',
            name='demo_systems_bike_class',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demo_systems_bike_class_changes', to='core.BikeClass'),
        ),
        migrations.AddField(
            model_name='reviewframeset',
            name='demo_frameset_frame_type',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demo_frameset_frame_type_changes', to='core.FrameType'),
        ),
        migrations.AddField(
            model_name='reviewframeset',
            name='demo_frameset_wheel_size',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demo_frameset_wheel_size_changes', to='core.WheelSize'),
        ),
        migrations.AddField(
            model_name='reviewgeneral',
            name='demo_bike_class',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demo_bike_class_changes', to='core.BikeClass'),
        ),
        migrations.AddField(
            model_name='reviewgeneral',
            name='demo_brake_type',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demo_brake_type_changes', to='core.BreakType'),
        ),
        migrations.AddField(
            model_name='reviewgeneral',
            name='demo_frame_type',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demo_frame_type_changes', to='core.FrameType'),
        ),
        migrations.AddField(
            model_name='reviewgeneral',
            name='demo_wheel_size',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demo_wheel_size_changes', to='core.WheelSize'),
        ),
    ]
