# Generated by Django 3.2.12 on 2022-08-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20220822_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
