# Generated by Django 3.2.12 on 2022-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_comments_is_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='demo_page_bike_class',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demo_page_bike_class_changes', to='core.BikeClass'),
        ),
    ]
