# Generated by Django 3.2.12 on 2022-09-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_comments_is_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpVoteReviewHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('review_highlight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reviewhighlights')),
            ],
            options={
                'verbose_name': 'upvote_review_highlight',
                'verbose_name_plural': 'upvote_review_highlights',
                'db_table': 'upvote_review_highlight',
            },
        ),
        migrations.AddIndex(
            model_name='upvotereviewhighlights',
            index=models.Index(fields=['id'], name='upvote_revi_id_c63dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='upvotereviewhighlights',
            index=models.Index(fields=['ip'], name='upvote_revi_ip_db6682_idx'),
        ),
    ]
