# Generated by Django 3.2.12 on 2022-09-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
