# Generated by Django 3.2.12 on 2022-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_contactus_is_spam'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=100)),
                ('type_name', models.CharField(max_length=150)),
                ('type_url', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor History',
                'verbose_name_plural': 'Visitor Histories',
                'db_table': 'visitor_history',
            },
        ),
        migrations.AddIndex(
            model_name='visitorhistory',
            index=models.Index(fields=['id'], name='visitor_his_id_df9ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorhistory',
            index=models.Index(fields=['ip', 'type'], name='visitor_his_ip_5c49a1_idx'),
        ),
    ]
